### ISSUE TITLE
The pypi version is outdated

### ISSUE THREAD

**Issue by felippemr** [db-art/mysql-statsd#45]
Exec ``` pip install mysql-statsd``` and compare this file(mysql_statsd/thread_mysql.py) with the master.

Pypi file appears to be out off sync with the repo.

**Comment by thijsdezoete** [comment]
Hi @felippemr. I'll look into it this week.

**Comment by thijsdezoete** [comment]
Hi @felippemr 
We'll upload a new version in just a bit. Please see the new config file (/docs/mysql-statsd.conf). 

If you need other support, don't hesitate to contact us / create a new issue.
